/**
 * Created by Ivan on 27.03.2014.
 */
public enum UserState {
    IS_ANONYMOUS,
    LOGGED_IN,
    AUTHORIZATION_ERROR,
    REGISTRATION_ERROR,
    WAITING_FOR_AUTHORIZATION,
    WAITING_FOR_REGISTRATION,
    WRONG_DATA_INPUT,
    JUST_REGISTERED
}
