package services.frontend;

/**
 * Created by Ivan on 27.03.2014 in 19:44.
 */
enum UserState {
    IS_ANONYMOUS,
    LOGGED_IN,
    AUTHORIZATION_ERROR,
    REGISTRATION_ERROR,
    WAITING_FOR_AUTHORIZATION,
    WAITING_FOR_REGISTRATION,
    WRONG_REGDATA_INPUT,
    WRONG_AUTHDATA_INPUT,
    JUST_REGISTERED
}